# Use an official Node.js image as a base image
FROM node:14-alpine

# Set the working directory
WORKDIR /app/server

# Copy package.json and package-lock.json
COPY server/package*.json ./

# Install dependencies
RUN npm ci

# Copy the server code
COPY server .

# Expose port 5000
EXPOSE 5000

# Command to run the server
CMD ["npm", "start"]
